### ISSUE TITLE
Can someone guide me on how to do a bottom sheet that only dismiss/expands when we scroll in the header part (which is fixed)?

### ISSUE THREAD

**Issue by ember11498** [surfstudio/flutter-bottom-sheet#105]
I want to make a bottom sheet where users can only dismiss or expand the bottom sheet when they scroll in the header part of the bottom sheet. And this header should always be fixed. The body part I want to be a listview that does not scroll when users scroll through the list.

Can someone guide me on a general skeleton of the code?

**Comment by internetova** [comment]
@ember11498 Hi!

From your description, it's not completely clear what needs to be done. Could you please provide a screenshot of the screen showing what and how it should work? Or a recording of the current implementation that you would like to adjust?

You can see examples of using the package here:
https://github.com/surfstudio/flutter-bottom-sheet/tree/main/example/lib
