### ISSUE TITLE
Make the barrier transparent

### ISSUE THREAD

**Issue by the100rabh** [surfstudio/flutter-bottom-sheet#29]
## What is the new or updated feature that you are suggesting?

Can the barrier which is shown be made configurable eg to force it to be transparent in certain cases or of other colors

## Why should this feature be included?

Gives added flexibility which is there in the bottomsheet widget.

**Comment by MbIXjkee** [comment]
UPD: For make it transparent you can use isModal=false, but colorize of this barrier unfortunately don't available yet.

**Comment by zaharovroman** [comment]
@the100rabh This feature was realized in https://github.com/surfstudio/flutter-bottom-sheet/pull/56
