### ISSUE TITLE
Add the opportunity to disable padding

### ISSUE THREAD

**Issue by bonsoirelliot** [surfstudio/flutter-bottom-sheet#30]
## What is the new or updated feature that you are suggesting?

Add the ability to disable the padding that appears when the keyboard is open.

## Why should this feature be included?

I had to add Scaffold to FlexibleBottomSheet to be able to scroll to the text field when clicking on it. Therefore, I had to remove the padding in FlexibleBottomSheet in order for the Scaffold's `resizeToAvoidBottomInset` to work properly.

**Comment by MbIXjkee** [comment]
Fixed in https://github.com/surfstudio/flutter-bottom-sheet/releases/tag/v3.0.0
