### ISSUE TITLE
Enable to dismiss bottom sheet at a specific height 

### ISSUE THREAD

**Issue by Anas-Othman** [surfstudio/flutter-bottom-sheet#34]
## Why should this feature be included?

Is your feature request related to a problem? Please describe a clear and concise description of what the problem is. If you investigated any alternative solutions please describe.

## Additional context

Please provide any other context or screenshots about the feature request here.

**Comment by MbIXjkee** [comment]
There is minHeight param for this behavior if i wright understand you.
