### ISSUE TITLE
[FEATURE REQUEST] Effective isModal: false

### ISSUE THREAD

**Issue by sirkalmi** [surfstudio/flutter-bottom-sheet#36]
This is the best bottom sheet I have found, but I have a little problem with it. I want the area above the bottom sheet to be active when isModal: false is set. For example, if there is a map there, it can be handled with the bottom sheet open.

**Comment by MbIXjkee** [comment]
Hi! This case looks like you have not to show bottomsheet as a separate route. Because when you show new route, all behind it become inactive. For your case bottomsheet and map should be active together. You have to use stack in one route in this case.
