### ISSUE TITLE
Set initial height based on content height

### ISSUE THREAD

**Issue by Ruslanbek0809** [surfstudio/flutter-bottom-sheet#38]

**Comment by MbIXjkee** [comment]
Hi! What functional do you want, please describe more detail?

**Comment by Ruslanbek0809** [comment]
Hi, surf studio team! It would be great if the initial height adjusts for incoming content height. I see you guys from Russia. You can check this for the Yandex Yeda app. When the bottom sheet appears, its initial height is adjusted based on incoming content height.

**Comment by Ruslanbek0809** [comment]
Yeah. For example, in Yandex Yeda if there are not any meal parameters and it has an only description, its bottom sheet will be smaller than the screen size and adjusts based on its description height

**Comment by KristinaZoteva** [comment]
@MbIXjkee Задача: Сделать так что бы размер BottomSheet мог зависеть от входящих данных, т е если размер входящих данных меньше чем высота BottomSheet которую мы задаем, то BottomSheet должен иметь высоту достаточную для отображения данных.
  	FlexibleBottomSheet принимает в себя minHeight, maxHeight, initHeight, builder(или bodyBuilder и headerBuilder). Билдеры возвращают контент, который должен отображаться в FlexibleBottomSheet, размер FlexibleBottomSheet зависит от переданных minHeight, maxHeight, initHeight, если их не передать, то эти значения будут работать со значениями по умолчанию(0.25, 0.5 и 1). FlexibleBottomSheet передает билдеры в виджет _Content, а он в свою очередь строит сам контент. 

Для решения этого вопроса было попробовано: 
В виджет FlexibleBottomSheet добавить post frame callback, который вызывается после построения макета и рассчитывает размер виджета _Content, затем делает setState и перестраивается с новыми значениями maxHeight и initHeight.
Так как виджет обернут в Expanded и Column действия выше не работают, потому что Expanded заставляет _Content занимать все доступное пространство, независимо от его реальных размеров. Я убрала виджеты Expanded и Column и обернула _Content  в Scaffold, вместе с ними я попробовала убрать виджет, которых достраивал внизу пустой контейнер при открытой клавиатуре. Со Scaffold была такая же ситуация как и с Expanded. В виджет _Content я решила передать функцию которая будет вызываться после его построения и принимать в себя размер возвращаемого билдерами виджетов, для этого я обернула билдер в SizedBox и передала ему ключ по которому в post frame callback рассчитывается высота виджетов, возвращаемых билдером и вызывается функция переданная в _Content с нужной высотой, а в этой функции осуществляется setState с новыми данными в maxHeight и initHeight. Для того что бы это работало пользователь должен передать скроллящийся виджет с указанным shrinkWrap: true(например: ListView( shrinkWrap: true)) и maxHeight и initHeight должны быть равны, а поле isExpand должно быть false чтобы определить что нам нужен размер исходя из размера контента. Этот вариант работал, но т к мы убрали контейнер, который достраивался снизу для того чтобы нужное поле TextField было в фокусе, а Scaffold в не поднимает BottomSheet над клавиатурой, сломался тот функционал, который корректно работал с открытием клавиатуры.

**Comment by MbIXjkee** [comment]
Added in https://github.com/surfstudio/flutter-bottom-sheet/releases/tag/v3.0.0
Example also available.
