### ISSUE TITLE
Feature to change default animation bottom sheet duration

### ISSUE THREAD

**Issue by Ruslanbek0809** [surfstudio/flutter-bottom-sheet#39]
Hi, surf studio team, 
Thanks for this great package. I would like to request a feature to change the default bottom sheet duration which is 500 milliseconds. The animation duration of opening and closing is too slow right now. When it is opening or closing if the user taps somewhere it pops the current page. The reason is duration time.

**Comment by MbIXjkee** [comment]
Hi! You are welcome! I'm not sure that is possible to change, because we use default some default Flutter entities. But we will research it and if it possible add this opportunity.

**Comment by Ruslanbek0809** [comment]
Default opening/closing animation duration of DraggableScrollableSheet is fast. And it is possible to change for this package. Could you look at line 18 `const Duration _bottomSheetDuration = Duration(milliseconds: 500);` for file `flexible_bottom_sheet_route.dart`? It is by default 500 milliseconds. You can modify the code so that others can change it manually.

**Comment by MbIXjkee** [comment]
Yes, that's right, we use our own route implementation and it will not be a problem. Thank you for your research.

**Comment by Ruslanbek0809** [comment]
When will you be able to push the new release with changes?

**Comment by MbIXjkee** [comment]
It will be in week-two i think

**Comment by Ruslanbek0809** [comment]
Thanks

**Comment by MbIXjkee** [comment]
Available in 2.1.0 version
