### ISSUE TITLE
[BUG] scroll to focus does not work when the keyboard is open in showStickyFlexibleBottomSheet.

### ISSUE THREAD

**Issue by KristinaZoteva** [surfstudio/flutter-bottom-sheet#48]
Scroll to focus does not work when the keyboard is open in showStickyFlexibleBottomSheet.

## Describe the bug

https://user-images.githubusercontent.com/72078435/162162141-e3efe93a-1880-4fdf-8416-72599bfc9d31.mp4

## What is the expected behavior?

When you open the keyboard, the TextField should scroll over it. Like here

https://user-images.githubusercontent.com/72078435/162162859-f15db6fc-1028-4c7c-93f3-9d1e1946fd51.mov

**Comment by MbIXjkee** [comment]
Fixed in https://github.com/surfstudio/flutter-bottom-sheet/releases/tag/v3.0.0
