### ISSUE TITLE
Flexible sheet decoration

### ISSUE THREAD

**Issue by Ilya-Vysotsky** [surfstudio/flutter-bottom-sheet#49]
A cant find a way to custom top left and right borders with radius. Is it possible now?

**Comment by MbIXjkee** [comment]
Hi! We have found that it is not works in the moment. But we already working to fix it and it will be coming soon.

**Comment by MbIXjkee** [comment]
Fixed in https://github.com/surfstudio/flutter-bottom-sheet/releases/tag/v3.0.0
