### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by treacks5** [surfstudio/flutter-bottom-sheet#53]
I would like to show the bottom sheet at the top of my navigation bar.

When I use my 'scaffoldStateKey' it is working with the flutter native solution `scaffoldStateKey.currentState?.showBottomSheet`, but not with this library.

My context is that I have a page (firstPage) nested inside a home page (homePage) that contains the navigation bar.

homePage :
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
        resizeToAvoidBottomInset: false,
        bottomNavigationBar: BottomNavBar(...),
        body: FirstPage();
  }
```

firstPage :
```dart
@override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        ...
        return false;
      },
      child: Scaffold(
          key: scaffoldStateKey,
          resizeToAvoidBottomInset: ...
          backgroundColor: ...
          body: screenBody()),
    );
  }

showFlexibleBottomSheet(
        context: scaffoldStateKey.currentState!.context,
        builder: _buildBottomSheet,
        isModal: false);
```

I also tried by adding a top-level scaffoldStateKey to my homePage scaffold widget (homeScaffoldStateKey) and use it. But same result happen.

With `scaffoldStateKey.currentState?.showBottomSheet` :
<img width="457" alt="Screenshot 2022-04-26 at 11 22 14" src="https://user-images.githubusercontent.com/53431511/165267906-c9aa1bff-23b8-4519-867c-d3e569594e66.png">
With `showFlexibleBottomSheet(context: scaffoldStateKey.currentState!.context,` :
<img width="472" alt="Screenshot 2022-04-26 at 11 23 39" src="https://user-images.githubusercontent.com/53431511/165268165-1829d8d3-fbdd-4378-a3aa-20254460b014.png">

## What is the expected behavior?

Having the modal bottom sheet shown at the top of my navigation bar. In the same way I use `scaffoldStateKey.currentState?.showBottomSheet`

**Comment by MbIXjkee** [comment]
Hi! When you use showFlexibleBottomSheet, you open new route this way. And it's not possible to show part of previous route above new one. If you want to have widget included into your layout, you have not to use showFlexibleBottomSheet and just insert widget into right place.
