### ISSUE TITLE
Is there any way to to set maxHeight depending on content height?

### ISSUE THREAD

**Issue by bonsoirelliot** [surfstudio/flutter-bottom-sheet#62]
## What is the new or updated feature that you are suggesting?

Opportunity to set maxHeight automatically of FlexibleBottomSheet depending on content height.

## Why should this feature be included?

Now it is very complicted to calculate ratio of widget height to screen height.

Thanks.

**Comment by Ruslanbek0809** [comment]
It is already implemented here: #38. Check it out.

**Comment by dshevchenkoo** [comment]
@bonsoirelliot Did the solution (https://github.com/surfstudio/flutter-bottom-sheet/issues/38) help you?
