### ISSUE TITLE
[BUG] Can't open on screen keyboard when showFlexibleBottomSheet based on content height is used

### ISSUE THREAD

**Issue by Ruslanbek0809** [surfstudio/flutter-bottom-sheet#71]
Thanks for the package. I can't open the on-screen keyboard when showFlexibleBottomSheet based on content height is used. Can you check and let me know if you get this issue as well?

**Comment by mark-kascheev** [comment]
@Ruslanbek0809 Hello! What do you mean? Can you attach video for example?

**Comment by jcmtyler** [comment]
Hello, not sure if this is the same thing, but I also came here to report an issue with the on-screen keyboard when using showFlexibleBottomSheet 3.1.2 and Flutter 3.7.7. Attached is a short video showing how I open the bottom sheet, but then when the keyboard appears it completely blocks the sheet so I can't see what I'm typing. Here's my usage:

```
showFlexibleBottomSheet<void>(
      minHeight: 0,
      initHeight: 1.0,
      maxHeight: 1.0,
      isCollapsible: true,
      isExpand: false,
      context: ctx,
      builder: (BuildContext context, ScrollController scrollController, double bottomSheetOffset) {
        return ListView(
          controller: scrollController,
          shrinkWrap: true,
          padding: EdgeInsets.all(10.0),
          children: [
            Text(
              selectedDay.longDateOnly(),
              textAlign: TextAlign.center,
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            ...events(appState, selectedDay),
            const SizedBox(height: 8.0),
            notes(context, appState, selectedDay),
          ],
        );
      },
      isSafeArea: true,
    );
```

![flexible_bottom_sheet_blocked_by_keyboard_25mar2023](https://user-images.githubusercontent.com/7539538/227707917-082d7347-47d7-479b-9e64-1be3fb5fb488.gif)
